from ..rpc import RpcClient
from ..models import OTAStatus

def check(client: RpcClient) -> OTAStatus: ...
def start(client: RpcClient, url: str | None = None) -> None: ...
def status(client: RpcClient) -> OTAStatus: ...
