from ..rpc import RpcClient
from ..models import SwitchState

def get_status(client: RpcClient, channel: int = 0) -> SwitchState: ...
def set_state(client: RpcClient, channel: int = 0, on: bool = True) -> SwitchState: ...
