from ..rpc import RpcClient

def get_config(client: RpcClient) -> dict: ...
def set_sta(client: RpcClient, ssid: str, passphrase: str,
            ipv4: str | None = None, gw: str | None = None, mask: str | None = None) -> None: ...
def connect(client: RpcClient) -> None: ...
